Feature/eodhp 239 update configuration
UKEODHP/eodhp-argocd-deployment pull request #38
Opened 2024-04-10 13:18 UTC by hcollingwood

Environment variables for allowed_hosts and base_url for use in web presence

2024-04-10 15:00 UTC, apalmer-tpzuk commented on apps/web-presence/envs/dev/kustomization.yaml
> +    version: 0.1.7-rc2
Is -rc2 intended?

2024-04-10 15:03 UTC, hcollingwood commented on apps/web-presence/envs/dev/kustomization.yaml
> +    version: 0.1.7-rc2
For now. James should update it to something else though

2024-04-11 08:24 UTC, sgillies-tpzuk commented on apps/web-presence/envs/dev/values.yaml
> +  allowed_hosts: .eodatahub.org.uk
is the leading dot intentional? does that allow for any subdomains? or should this be dev.eodatahub.org.uk?

2024-04-11 08:25 UTC, hcollingwood commented on apps/web-presence/envs/dev/values.yaml
> +  allowed_hosts: .eodatahub.org.uk
It is intentional for all subdomains. Happy to further restrict if required

2024-04-11 10:33 UTC, ahaywardtvuk commented on apps/web-presence/envs/dev/values.yaml
> +  allowed_hosts: .eodatahub.org.uk
It's preferable to further restrict this (as I understand it this only needs to be the domain(s) that Wagtail or any other Django apps will serve content for).

An example of a scenario where it could be an issue is:
* An attacker compromises a test or development cluster, or any other service under the .eodatahub.org.uk domain.
* The attacker manages to make a request to Wagtail with the header `Host: compromised.eodatahub.org.uk`.
* Wagtail uses the Host header to generate links in the page, such as https://compromised.eodatahub.org.uk/login/
* This page or page fragment is cached, for example in the Django template caches or nginx.
* The next user to go to the site gets a login link pointing to https://compromised.eodatahub.org.uk/login/ instead of the real one.

2024-04-11 10:41 UTC, sgillies-tpzuk requested changes

2024-04-11 10:41 UTC, sgillies-tpzuk commented on apps/web-presence/envs/dev/values.yaml
> +  allowed_hosts: .eodatahub.org.uk
Yes, I agree with Alex, we want to restrict this further. please set to dev.eodatahub.org.uk, thanks.

2024-04-15 13:12 UTC, merged